# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=50)),
                ('date', models.DateField(blank=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('min', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max', models.DecimalField(decimal_places=6, max_digits=10)),
                ('close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('change', models.DecimalField(decimal_places=6, max_digits=10)),
                ('percentage', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
