# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='change',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
