# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171127_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='max',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='min',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
