# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171127_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='max',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='min',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
