# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('close', models.FloatField()),
                ('change', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
